In [4]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (6.31.1)
Requirement already satisfied: requests<3,>=2.21.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (2.33.1)
Requirement already satisfied: setuptools in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (75.8.0)
Requirement already satisfied: six>=1.12.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (1.81.1)
Requirement already satisfied: keras>=3.12.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (2.3.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: wheel<1.0,>=0.23.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\anime\AppData\Roaming\Python\Python313\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [16]:
# ==========================================
# Import Required Libraries
# ==========================================

# Numerical Computing
import numpy as np

# Data Manipulation
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# Deep Learning
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Set Random Seed for Reproducibility
np.random.seed(42)
tf.random.set_seed(42)

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.21.0

In [17]:
# ==========================================
# Create Smart Irrigation Dataset
# ==========================================

df = pd.DataFrame({
    "soil_moisture": [
        0.08, 0.12, 0.18, 0.22, 0.28, 0.35, 0.42, 0.50, 0.58, 0.65,
        0.72, 0.80, 0.15, 0.25, 0.33, 0.45, 0.55, 0.62, 0.10, 0.20,
        0.30, 0.40, 0.52, 0.68, 0.75, 0.18, 0.27, 0.38, 0.48, 0.60
    ],

    "temperature_c": [
        36, 34, 32, 30, 28, 27, 26, 29, 31, 33,
        35, 37, 25, 24, 23, 26, 28, 30, 38, 35,
        32, 29, 27, 25, 24, 36, 31, 28, 26, 34
    ],

    "sunlight_hours": [
        10, 9, 8, 7, 6, 5, 4, 7, 8, 9,
        11, 12, 3, 4, 5, 6, 7, 8, 10, 9,
        8, 7, 6, 5, 4, 11, 9, 6, 5, 10
    ],

    "humidity": [
        30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 50, 55, 60, 65, 70, 75, 35, 40,
        45, 50, 60, 70, 80, 30, 45, 55, 65, 75
    ],

    "rainfall_mm": [
        0, 0, 2, 5, 10, 15, 20, 8, 5, 2,
        0, 0, 18, 22, 25, 12, 8, 5, 0, 1,
        3, 10, 18, 22, 28, 0, 2, 12, 18, 0
    ],

    "need_water": [
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 0
    ]
})

# Display first five rows
df.head()

,soil_moisture,temperature_c,sunlight_hours,humidity,rainfall_mm,need_water
0,0.08,36,10,30,0,1
1,0.12,34,9,35,0,1
2,0.18,32,8,40,2,1
3,0.22,30,7,45,5,1
4,0.28,28,6,50,10,0

In [7]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'need_water'], dtype='object')

In [18]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours', 'humidity', 'rainfall_mm']]
y = df['need_water']

In [19]:
from sklearn.preprocessing import MinMaxScaler

# ==========================================
# Feature Scaling using MinMaxScaler
# ==========================================

scaler = MinMaxScaler()

X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns
)

# View scaled data
X_scaled.head()

   soil_moisture  temperature_c  sunlight_hours  humidity  rainfall_mm
0       0.000000       0.866667        0.777778  0.000000     0.000000
1       0.055556       0.733333        0.666667  0.090909     0.000000
2       0.138889       0.600000        0.555556  0.181818     0.071429
3       0.194444       0.466667        0.444444  0.272727     0.178571
4       0.277778       0.333333        0.333333  0.363636     0.357143

In [20]:
# ==========================================
# Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y,
    shuffle=True
)

print("Training Samples :", X_train.shape[0])
print("Testing Samples  :", X_test.shape[0])

# ==========================================
# Build Artificial Neural Network (ANN)
# ==========================================

model = keras.Sequential([

    # Input Layer (5 features)
    layers.Input(shape=(X_train.shape[1],)),

    # Hidden Layer 1
    layers.Dense(
        16,
        activation="relu",
        kernel_initializer="he_normal"
    ),
    layers.Dropout(0.20),

    # Hidden Layer 2
    layers.Dense(
        8,
        activation="relu"
    ),

    # Output Layer
    layers.Dense(
        1,
        activation="sigmoid"
    )
])

# Display Model Architecture
model.summary()

Training Samples : 24
Testing Samples  : 6

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape          ┃      Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ dense_3 (Dense)               │ (None, 16)            │           96 │
├───────────────────────────────┼───────────────────────┼──────────────┤
│ dropout_1 (Dropout)           │ (None, 16)            │            0 │
├───────────────────────────────┼───────────────────────┼──────────────┤
│ dense_4 (Dense)               │ (None, 8)             │          136 │
├───────────────────────────────┼───────────────────────┼──────────────┤
│ dense_5 (Dense)               │ (None, 1)             │            9 │
└───────────────────────────────┴───────────────────────┴──────────────┘

 Total params: 241 (964.00 B)

 Trainable params: 241 (964.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
# ==========================================
# Function to Build ANN Model
# ==========================================

def build_model():

    model = keras.Sequential([

        layers.Input(shape=(X_train.shape[1],)),

        layers.Dense(
            16,
            activation="relu",
            kernel_initializer="he_normal"
        ),

        layers.Dropout(0.20),

        layers.Dense(
            8,
            activation="relu"
        ),

        layers.Dense(
            1,
            activation="sigmoid"
        )
    ])

    optimizer = keras.optimizers.Adam(learning_rate=0.001)

    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    return model

In [22]:
print("="*50)
print("Training using Full Batch Gradient Descent")
print("="*50)

model_full = build_model()

history_full = model_full.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=len(X_train),
    verbose=1
)

==================================================
Training using Full Batch Gradient Descent
==================================================
Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3158 - loss: 1.2818 - val_accuracy: 0.6000 - val_loss: 0.8331
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3158 - loss: 1.3751 - val_accuracy: 0.6000 - val_loss: 0.8258
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3158 - loss: 1.3840 - val_accuracy: 0.6000 - val_loss: 0.8185
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3158 - loss: 1.3761 - val_accuracy: 0.6000 - val_loss: 0.8113
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.3158 - loss: 1.1788 - val_accuracy: 0.6000 - val_loss: 0.8042
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3158 - loss: 1.2397 - val_accuracy: 0.6000 - val_loss: 0.7975
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.3158 - loss: 1.3611 - val_accuracy: 0.6000 - val_loss: 0.7908
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3158 - loss: 1.2428 - val_accuracy: 0.6000 - val_loss: 0.7843
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3158 - loss: 1.2504 - val_accuracy: 0.6000 - val_loss: 0.7780
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3158 - loss: 1.0846 - val_accuracy: 0.6000 - val_loss: 0.7719
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.3158 - loss: 1.1966 - val_accuracy: 0.6000 - val_loss: 0.7659
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3158 - loss: 1.1092 - val_accuracy: 0.6000 - val_loss: 0.7600
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.3158 - loss: 1.1972 - val_accuracy: 0.6000 - val_loss: 0.7538
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3158 - loss: 1.0202 - val_accuracy: 0.6000 - val_loss: 0.7470
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.2632 - loss: 1.2277 - val_accuracy: 0.6000 - val_loss: 0.7397
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3158 - loss: 1.1561 - val_accuracy: 0.6000 - val_loss: 0.7324
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3158 - loss: 1.0342 - val_accuracy: 0.6000 - val_loss: 0.7255
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3158 - loss: 1.0655 - val_accuracy: 0.6000 - val_loss: 0.7186
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.3158 - loss: 1.0009 - val_accuracy: 0.6000 - val_loss: 0.7120
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3684 - loss: 0.9153 - val_accuracy: 0.6000 - val_loss: 0.7057
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3158 - loss: 1.0019 - val_accuracy: 0.6000 - val_loss: 0.6995
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3158 - loss: 0.9950 - val_accuracy: 0.6000 - val_loss: 0.6935
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3158 - loss: 1.0609 - val_accuracy: 0.6000 - val_loss: 0.6878
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3158 - loss: 1.0140 - val_accuracy: 0.6000 - val_loss: 0.6823
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3158 - loss: 0.9758 - val_accuracy: 0.6000 - val_loss: 0.6769
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.2632 - loss: 1.0399 - val_accuracy: 0.6000 - val_loss: 0.6714
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3158 - loss: 0.9630 - val_accuracy: 0.6000 - val_loss: 0.6661
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3158 - loss: 0.8903 - val_accuracy: 0.6000 - val_loss: 0.6609
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.3158 - loss: 0.8448 - val_accuracy: 0.6000 - val_loss: 0.6561
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3684 - loss: 0.8493 - val_accuracy: 0.6000 - val_loss: 0.6521
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3684 - loss: 0.8889 - val_accuracy: 0.6000 - val_loss: 0.6483
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3158 - loss: 0.8699 - val_accuracy: 0.6000 - val_loss: 0.6447
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.2632 - loss: 0.8619 - val_accuracy: 0.6000 - val_loss: 0.6411
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3158 - loss: 0.8545 - val_accuracy: 0.6000 - val_loss: 0.6374
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3684 - loss: 0.8218 - val_accuracy: 0.6000 - val_loss: 0.6334
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.3158 - loss: 0.8470 - val_accuracy: 0.6000 - val_loss: 0.6300
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3684 - loss: 0.9232 - val_accuracy: 0.6000 - val_loss: 0.6267
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4211 - loss: 0.8367 - val_accuracy: 0.6000 - val_loss: 0.6242
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3158 - loss: 0.8519 - val_accuracy: 0.6000 - val_loss: 0.6221
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4211 - loss: 0.8041 - val_accuracy: 0.8000 - val_loss: 0.6209
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3158 - loss: 0.8794 - val_accuracy: 0.8000 - val_loss: 0.6197
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3684 - loss: 0.8114 - val_accuracy: 0.8000 - val_loss: 0.6186
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3158 - loss: 0.9175 - val_accuracy: 0.8000 - val_loss: 0.6174
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3684 - loss: 0.7833 - val_accuracy: 0.8000 - val_loss: 0.6161
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3158 - loss: 0.7984 - val_accuracy: 0.8000 - val_loss: 0.6148
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.3684 - loss: 0.7421 - val_accuracy: 0.8000 - val_loss: 0.6141
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3158 - loss: 0.8525 - val_accuracy: 0.8000 - val_loss: 0.6133
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.3684 - loss: 0.7802 - val_accuracy: 0.8000 - val_loss: 0.6123
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3684 - loss: 0.8285 - val_accuracy: 0.8000 - val_loss: 0.6114
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.4737 - loss: 0.7584 - val_accuracy: 0.8000 - val_loss: 0.6106
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.4211 - loss: 0.7395 - val_accuracy: 0.8000 - val_loss: 0.6097
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5263 - loss: 0.7135 - val_accuracy: 1.0000 - val_loss: 0.6088
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.2632 - loss: 0.7993 - val_accuracy: 1.0000 - val_loss: 0.6079
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.4737 - loss: 0.7274 - val_accuracy: 1.0000 - val_loss: 0.6070
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4737 - loss: 0.7582 - val_accuracy: 1.0000 - val_loss: 0.6061
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.4737 - loss: 0.7581 - val_accuracy: 1.0000 - val_loss: 0.6052
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5263 - loss: 0.7553 - val_accuracy: 1.0000 - val_loss: 0.6045
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6316 - loss: 0.7196 - val_accuracy: 1.0000 - val_loss: 0.6037
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5789 - loss: 0.7218 - val_accuracy: 1.0000 - val_loss: 0.6028
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5789 - loss: 0.7716 - val_accuracy: 1.0000 - val_loss: 0.6020
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6316 - loss: 0.7236 - val_accuracy: 1.0000 - val_loss: 0.6012
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.6316 - loss: 0.7328 - val_accuracy: 1.0000 - val_loss: 0.6002
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.4211 - loss: 0.7477 - val_accuracy: 1.0000 - val_loss: 0.5995
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.3684 - loss: 0.8185 - val_accuracy: 1.0000 - val_loss: 0.5987
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6842 - loss: 0.6607 - val_accuracy: 1.0000 - val_loss: 0.5980
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6842 - loss: 0.7282 - val_accuracy: 1.0000 - val_loss: 0.5971
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6316 - loss: 0.7299 - val_accuracy: 1.0000 - val_loss: 0.5963
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.4737 - loss: 0.7367 - val_accuracy: 1.0000 - val_loss: 0.5955
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4737 - loss: 0.7314 - val_accuracy: 1.0000 - val_loss: 0.5946
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6842 - loss: 0.6913 - val_accuracy: 1.0000 - val_loss: 0.5938
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6842 - loss: 0.6411 - val_accuracy: 1.0000 - val_loss: 0.5929
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5789 - loss: 0.6625 - val_accuracy: 1.0000 - val_loss: 0.5920
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6842 - loss: 0.7012 - val_accuracy: 1.0000 - val_loss: 0.5911
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7895 - loss: 0.6573 - val_accuracy: 1.0000 - val_loss: 0.5900
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5263 - loss: 0.7392 - val_accuracy: 1.0000 - val_loss: 0.5889
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6316 - loss: 0.6842 - val_accuracy: 0.8000 - val_loss: 0.5878
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.5263 - loss: 0.7744 - val_accuracy: 0.8000 - val_loss: 0.5867
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7895 - loss: 0.6495 - val_accuracy: 0.8000 - val_loss: 0.5857
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7895 - loss: 0.6290 - val_accuracy: 0.8000 - val_loss: 0.5847
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5789 - loss: 0.7056 - val_accuracy: 0.8000 - val_loss: 0.5838
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8421 - loss: 0.6475 - val_accuracy: 0.8000 - val_loss: 0.5826
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7895 - loss: 0.6299 - val_accuracy: 0.8000 - val_loss: 0.5816
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6842 - loss: 0.6350 - val_accuracy: 0.8000 - val_loss: 0.5806
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6842 - loss: 0.6375 - val_accuracy: 0.8000 - val_loss: 0.5794
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5263 - loss: 0.6933 - val_accuracy: 0.8000 - val_loss: 0.5783
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.6842 - loss: 0.6758 - val_accuracy: 0.8000 - val_loss: 0.5771
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6842 - loss: 0.6249 - val_accuracy: 0.8000 - val_loss: 0.5760
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7368 - loss: 0.6173 - val_accuracy: 0.8000 - val_loss: 0.5749
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5789 - loss: 0.6818 - val_accuracy: 0.8000 - val_loss: 0.5737
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.8947 - loss: 0.6112 - val_accuracy: 0.8000 - val_loss: 0.5729
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.6842 - loss: 0.6216 - val_accuracy: 0.8000 - val_loss: 0.5720
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6842 - loss: 0.6349 - val_accuracy: 0.8000 - val_loss: 0.5710
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5789 - loss: 0.6476 - val_accuracy: 0.8000 - val_loss: 0.5701
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 1.0000 - loss: 0.5586 - val_accuracy: 0.8000 - val_loss: 0.5692
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.6842 - loss: 0.6204 - val_accuracy: 0.8000 - val_loss: 0.5682
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.8421 - loss: 0.6142 - val_accuracy: 0.8000 - val_loss: 0.5673
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7895 - loss: 0.6170 - val_accuracy: 0.8000 - val_loss: 0.5665
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6842 - loss: 0.6583 - val_accuracy: 0.8000 - val_loss: 0.5656
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7368 - loss: 0.6775 - val_accuracy: 0.8000 - val_loss: 0.5648
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5789 - loss: 0.6511 - val_accuracy: 0.8000 - val_loss: 0.5639

In [23]:
print("="*50)
print("Training using Stochastic Gradient Descent")
print("="*50)

model_sgd = build_model()

history_sgd = model_sgd.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=1,
    verbose=1
)

==================================================
Training using Stochastic Gradient Descent
==================================================
Epoch 1/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.3158 - loss: 1.0324 - val_accuracy: 0.6000 - val_loss: 0.5484
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3684 - loss: 0.8864 - val_accuracy: 0.6000 - val_loss: 0.4989
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4211 - loss: 0.8368 - val_accuracy: 0.6000 - val_loss: 0.4650
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3158 - loss: 0.8120 - val_accuracy: 0.8000 - val_loss: 0.4403
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4737 - loss: 0.6355 - val_accuracy: 0.8000 - val_loss: 0.4276
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6316 - loss: 0.6831 - val_accuracy: 1.0000 - val_loss: 0.4186
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6842 - loss: 0.6512 - val_accuracy: 1.0000 - val_loss: 0.4253
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7895 - loss: 0.5647 - val_accuracy: 1.0000 - val_loss: 0.4236
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6842 - loss: 0.6404 - val_accuracy: 1.0000 - val_loss: 0.4212
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7895 - loss: 0.5868 - val_accuracy: 1.0000 - val_loss: 0.4196
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8947 - loss: 0.5203 - val_accuracy: 1.0000 - val_loss: 0.4158
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7895 - loss: 0.5173 - val_accuracy: 1.0000 - val_loss: 0.4064
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6842 - loss: 0.5394 - val_accuracy: 1.0000 - val_loss: 0.4036
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8421 - loss: 0.4785 - val_accuracy: 1.0000 - val_loss: 0.4033
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.4736 - val_accuracy: 1.0000 - val_loss: 0.3959
Epoch 16/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.4257 - val_accuracy: 1.0000 - val_loss: 0.3840
Epoch 17/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8421 - loss: 0.4576 - val_accuracy: 1.0000 - val_loss: 0.3726
Epoch 18/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7895 - loss: 0.4433 - val_accuracy: 1.0000 - val_loss: 0.3592
Epoch 19/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.4584 - val_accuracy: 1.0000 - val_loss: 0.3494
Epoch 20/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.4244 - val_accuracy: 1.0000 - val_loss: 0.3359
Epoch 21/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8421 - loss: 0.4395 - val_accuracy: 1.0000 - val_loss: 0.3203
Epoch 22/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8421 - loss: 0.3860 - val_accuracy: 1.0000 - val_loss: 0.3127
Epoch 23/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8421 - loss: 0.3937 - val_accuracy: 1.0000 - val_loss: 0.3042
Epoch 24/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7895 - loss: 0.4404 - val_accuracy: 1.0000 - val_loss: 0.2944
Epoch 25/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.4239 - val_accuracy: 1.0000 - val_loss: 0.2928
Epoch 26/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8421 - loss: 0.3726 - val_accuracy: 1.0000 - val_loss: 0.2809
Epoch 27/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8421 - loss: 0.4136 - val_accuracy: 1.0000 - val_loss: 0.2619
Epoch 28/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7368 - loss: 0.4473 - val_accuracy: 1.0000 - val_loss: 0.2494
Epoch 29/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8947 - loss: 0.3233 - val_accuracy: 1.0000 - val_loss: 0.2354
Epoch 30/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8947 - loss: 0.3535 - val_accuracy: 1.0000 - val_loss: 0.2228
Epoch 31/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8947 - loss: 0.2709 - val_accuracy: 1.0000 - val_loss: 0.2060
Epoch 32/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9474 - loss: 0.3005 - val_accuracy: 1.0000 - val_loss: 0.1951
Epoch 33/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.3165 - val_accuracy: 1.0000 - val_loss: 0.1909
Epoch 34/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9474 - loss: 0.3225 - val_accuracy: 1.0000 - val_loss: 0.1856
Epoch 35/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.3591 - val_accuracy: 1.0000 - val_loss: 0.1802
Epoch 36/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.2961 - val_accuracy: 1.0000 - val_loss: 0.1694
Epoch 37/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.3239 - val_accuracy: 1.0000 - val_loss: 0.1616
Epoch 38/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8421 - loss: 0.3105 - val_accuracy: 1.0000 - val_loss: 0.1530
Epoch 39/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2784 - val_accuracy: 1.0000 - val_loss: 0.1492
Epoch 40/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.2544 - val_accuracy: 1.0000 - val_loss: 0.1445
Epoch 41/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.3193 - val_accuracy: 1.0000 - val_loss: 0.1429
Epoch 42/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8421 - loss: 0.2912 - val_accuracy: 1.0000 - val_loss: 0.1376
Epoch 43/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.2609 - val_accuracy: 1.0000 - val_loss: 0.1320
Epoch 44/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.2605 - val_accuracy: 1.0000 - val_loss: 0.1297
Epoch 45/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9474 - loss: 0.2791 - val_accuracy: 1.0000 - val_loss: 0.1255
Epoch 46/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1815 - val_accuracy: 1.0000 - val_loss: 0.1215
Epoch 47/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2496 - val_accuracy: 1.0000 - val_loss: 0.1168
Epoch 48/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2580 - val_accuracy: 1.0000 - val_loss: 0.1124
Epoch 49/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1636 - val_accuracy: 1.0000 - val_loss: 0.1105
Epoch 50/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.2590 - val_accuracy: 1.0000 - val_loss: 0.1078
Epoch 51/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.2134 - val_accuracy: 1.0000 - val_loss: 0.1077
Epoch 52/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8947 - loss: 0.2682 - val_accuracy: 1.0000 - val_loss: 0.1057
Epoch 53/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.1976 - val_accuracy: 1.0000 - val_loss: 0.1043
Epoch 54/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.3163 - val_accuracy: 1.0000 - val_loss: 0.1019
Epoch 55/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1883 - val_accuracy: 1.0000 - val_loss: 0.0991
Epoch 56/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2064 - val_accuracy: 1.0000 - val_loss: 0.0965
Epoch 57/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2322 - val_accuracy: 1.0000 - val_loss: 0.0942
Epoch 58/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1996 - val_accuracy: 1.0000 - val_loss: 0.0930
Epoch 59/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9474 - loss: 0.2005 - val_accuracy: 1.0000 - val_loss: 0.0922
Epoch 60/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2308 - val_accuracy: 1.0000 - val_loss: 0.0920
Epoch 61/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.2904 - val_accuracy: 1.0000 - val_loss: 0.0891
Epoch 62/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2580 - val_accuracy: 1.0000 - val_loss: 0.0865
Epoch 63/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1564 - val_accuracy: 1.0000 - val_loss: 0.0860
Epoch 64/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2013 - val_accuracy: 1.0000 - val_loss: 0.0880
Epoch 65/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1557 - val_accuracy: 1.0000 - val_loss: 0.0897
Epoch 66/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.2111 - val_accuracy: 1.0000 - val_loss: 0.0895
Epoch 67/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.2383 - val_accuracy: 1.0000 - val_loss: 0.0850
Epoch 68/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1714 - val_accuracy: 1.0000 - val_loss: 0.0817
Epoch 69/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1738 - val_accuracy: 1.0000 - val_loss: 0.0790
Epoch 70/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2076 - val_accuracy: 1.0000 - val_loss: 0.0775
Epoch 71/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1732 - val_accuracy: 1.0000 - val_loss: 0.0759
Epoch 72/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.1795 - val_accuracy: 1.0000 - val_loss: 0.0741
Epoch 73/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9474 - loss: 0.1794 - val_accuracy: 1.0000 - val_loss: 0.0720
Epoch 74/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.2071 - val_accuracy: 1.0000 - val_loss: 0.0719
Epoch 75/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1797 - val_accuracy: 1.0000 - val_loss: 0.0721
Epoch 76/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2323 - val_accuracy: 1.0000 - val_loss: 0.0741
Epoch 77/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2139 - val_accuracy: 1.0000 - val_loss: 0.0771
Epoch 78/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1640 - val_accuracy: 1.0000 - val_loss: 0.0794
Epoch 79/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9474 - loss: 0.1471 - val_accuracy: 1.0000 - val_loss: 0.0784
Epoch 80/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1849 - val_accuracy: 1.0000 - val_loss: 0.0730
Epoch 81/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2140 - val_accuracy: 1.0000 - val_loss: 0.0724
Epoch 82/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.2272 - val_accuracy: 1.0000 - val_loss: 0.0688
Epoch 83/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.1819 - val_accuracy: 1.0000 - val_loss: 0.0684
Epoch 84/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1634 - val_accuracy: 1.0000 - val_loss: 0.0658
Epoch 85/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1253 - val_accuracy: 1.0000 - val_loss: 0.0669
Epoch 86/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9474 - loss: 0.1680 - val_accuracy: 1.0000 - val_loss: 0.0666
Epoch 87/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8947 - loss: 0.2190 - val_accuracy: 1.0000 - val_loss: 0.0631
Epoch 88/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1229 - val_accuracy: 1.0000 - val_loss: 0.0622
Epoch 89/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.2662 - val_accuracy: 1.0000 - val_loss: 0.0611
Epoch 90/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1819 - val_accuracy: 1.0000 - val_loss: 0.0595
Epoch 91/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1649 - val_accuracy: 1.0000 - val_loss: 0.0607
Epoch 92/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1593 - val_accuracy: 1.0000 - val_loss: 0.0598
Epoch 93/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1433 - val_accuracy: 1.0000 - val_loss: 0.0625
Epoch 94/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.1086 - val_accuracy: 1.0000 - val_loss: 0.0618
Epoch 95/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1446 - val_accuracy: 1.0000 - val_loss: 0.0618
Epoch 96/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1671 - val_accuracy: 1.0000 - val_loss: 0.0618
Epoch 97/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9474 - loss: 0.1213 - val_accuracy: 1.0000 - val_loss: 0.0637
Epoch 98/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.1441 - val_accuracy: 1.0000 - val_loss: 0.0588
Epoch 99/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8947 - loss: 0.2580 - val_accuracy: 1.0000 - val_loss: 0.0527
Epoch 100/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8947 - loss: 0.2379 - val_accuracy: 1.0000 - val_loss: 0.0524

In [24]:
print("="*50)
print("Training using Mini-Batch Gradient Descent")
print("="*50)

model_mini = build_model()

history_mini = model_mini.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=4,
    verbose=1
)

==================================================
Training using Mini-Batch Gradient Descent
==================================================
Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.6842 - loss: 0.6436 - val_accuracy: 0.4000 - val_loss: 0.8617
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6842 - loss: 0.6374 - val_accuracy: 0.4000 - val_loss: 0.8450
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6842 - loss: 0.6139 - val_accuracy: 0.4000 - val_loss: 0.8275
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6842 - loss: 0.5972 - val_accuracy: 0.4000 - val_loss: 0.8111
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6842 - loss: 0.5976 - val_accuracy: 0.4000 - val_loss: 0.7973
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6842 - loss: 0.5617 - val_accuracy: 0.4000 - val_loss: 0.7813
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6842 - loss: 0.5443 - val_accuracy: 0.4000 - val_loss: 0.7661
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6842 - loss: 0.5365 - val_accuracy: 0.4000 - val_loss: 0.7512
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6842 - loss: 0.5484 - val_accuracy: 0.4000 - val_loss: 0.7361
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6842 - loss: 0.5451 - val_accuracy: 0.4000 - val_loss: 0.7207
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6842 - loss: 0.5706 - val_accuracy: 0.4000 - val_loss: 0.7047
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6842 - loss: 0.5100 - val_accuracy: 0.4000 - val_loss: 0.6889
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6842 - loss: 0.5472 - val_accuracy: 0.4000 - val_loss: 0.6758
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6842 - loss: 0.5390 - val_accuracy: 0.4000 - val_loss: 0.6624
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7368 - loss: 0.5100 - val_accuracy: 0.4000 - val_loss: 0.6491
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7368 - loss: 0.5248 - val_accuracy: 0.4000 - val_loss: 0.6366
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6842 - loss: 0.4545 - val_accuracy: 0.4000 - val_loss: 0.6247
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7368 - loss: 0.4934 - val_accuracy: 0.4000 - val_loss: 0.6119
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7368 - loss: 0.4447 - val_accuracy: 0.4000 - val_loss: 0.5974
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7368 - loss: 0.5045 - val_accuracy: 0.4000 - val_loss: 0.5812
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6842 - loss: 0.4649 - val_accuracy: 0.4000 - val_loss: 0.5658
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7895 - loss: 0.4943 - val_accuracy: 0.4000 - val_loss: 0.5515
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8421 - loss: 0.4382 - val_accuracy: 0.8000 - val_loss: 0.5386
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8421 - loss: 0.4354 - val_accuracy: 0.8000 - val_loss: 0.5243
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7895 - loss: 0.4610 - val_accuracy: 0.8000 - val_loss: 0.5095
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7368 - loss: 0.4572 - val_accuracy: 0.8000 - val_loss: 0.4950
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8421 - loss: 0.5016 - val_accuracy: 0.8000 - val_loss: 0.4807
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7895 - loss: 0.4547 - val_accuracy: 0.8000 - val_loss: 0.4674
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8421 - loss: 0.4154 - val_accuracy: 0.8000 - val_loss: 0.4538
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7895 - loss: 0.4159 - val_accuracy: 1.0000 - val_loss: 0.4413
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8421 - loss: 0.4206 - val_accuracy: 1.0000 - val_loss: 0.4300
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8421 - loss: 0.4247 - val_accuracy: 1.0000 - val_loss: 0.4202
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7895 - loss: 0.4964 - val_accuracy: 1.0000 - val_loss: 0.4104
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8421 - loss: 0.4255 - val_accuracy: 1.0000 - val_loss: 0.3999
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8421 - loss: 0.3668 - val_accuracy: 1.0000 - val_loss: 0.3879
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9474 - loss: 0.3627 - val_accuracy: 1.0000 - val_loss: 0.3761
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8421 - loss: 0.4291 - val_accuracy: 1.0000 - val_loss: 0.3641
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.3988 - val_accuracy: 1.0000 - val_loss: 0.3531
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8421 - loss: 0.4351 - val_accuracy: 1.0000 - val_loss: 0.3431
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.3491 - val_accuracy: 1.0000 - val_loss: 0.3342
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8421 - loss: 0.4107 - val_accuracy: 1.0000 - val_loss: 0.3259
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8947 - loss: 0.3709 - val_accuracy: 1.0000 - val_loss: 0.3180
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8421 - loss: 0.3687 - val_accuracy: 1.0000 - val_loss: 0.3105
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9474 - loss: 0.3824 - val_accuracy: 1.0000 - val_loss: 0.3033
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8947 - loss: 0.3628 - val_accuracy: 1.0000 - val_loss: 0.2964
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8421 - loss: 0.3628 - val_accuracy: 1.0000 - val_loss: 0.2900
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8421 - loss: 0.3605 - val_accuracy: 1.0000 - val_loss: 0.2828
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9474 - loss: 0.3204 - val_accuracy: 1.0000 - val_loss: 0.2754
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9474 - loss: 0.2822 - val_accuracy: 1.0000 - val_loss: 0.2677
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8421 - loss: 0.4178 - val_accuracy: 1.0000 - val_loss: 0.2600
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8947 - loss: 0.3422 - val_accuracy: 1.0000 - val_loss: 0.2534
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.3041 - val_accuracy: 1.0000 - val_loss: 0.2472
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.3255 - val_accuracy: 1.0000 - val_loss: 0.2413
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.3162 - val_accuracy: 1.0000 - val_loss: 0.2362
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.3064 - val_accuracy: 1.0000 - val_loss: 0.2306
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8421 - loss: 0.3438 - val_accuracy: 1.0000 - val_loss: 0.2255
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2673 - val_accuracy: 1.0000 - val_loss: 0.2199
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2927 - val_accuracy: 1.0000 - val_loss: 0.2143
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.3717 - val_accuracy: 1.0000 - val_loss: 0.2091
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8947 - loss: 0.3282 - val_accuracy: 1.0000 - val_loss: 0.2041
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2118 - val_accuracy: 1.0000 - val_loss: 0.1994
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8947 - loss: 0.3635 - val_accuracy: 1.0000 - val_loss: 0.1955
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2841 - val_accuracy: 1.0000 - val_loss: 0.1915
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.3375 - val_accuracy: 1.0000 - val_loss: 0.1870
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8947 - loss: 0.3121 - val_accuracy: 1.0000 - val_loss: 0.1826
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2865 - val_accuracy: 1.0000 - val_loss: 0.1783
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2929 - val_accuracy: 1.0000 - val_loss: 0.1748
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9474 - loss: 0.3361 - val_accuracy: 1.0000 - val_loss: 0.1720
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2563 - val_accuracy: 1.0000 - val_loss: 0.1688
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.3014 - val_accuracy: 1.0000 - val_loss: 0.1658
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2490 - val_accuracy: 1.0000 - val_loss: 0.1630
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8421 - loss: 0.3261 - val_accuracy: 1.0000 - val_loss: 0.1604
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8421 - loss: 0.2713 - val_accuracy: 1.0000 - val_loss: 0.1576
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2819 - val_accuracy: 1.0000 - val_loss: 0.1557
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8421 - loss: 0.3321 - val_accuracy: 1.0000 - val_loss: 0.1543
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2228 - val_accuracy: 1.0000 - val_loss: 0.1526
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2520 - val_accuracy: 1.0000 - val_loss: 0.1506
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2440 - val_accuracy: 1.0000 - val_loss: 0.1490
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2487 - val_accuracy: 1.0000 - val_loss: 0.1470
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2587 - val_accuracy: 1.0000 - val_loss: 0.1447
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9474 - loss: 0.2531 - val_accuracy: 1.0000 - val_loss: 0.1424
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2332 - val_accuracy: 1.0000 - val_loss: 0.1407
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.1905 - val_accuracy: 1.0000 - val_loss: 0.1385
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2691 - val_accuracy: 1.0000 - val_loss: 0.1355
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2704 - val_accuracy: 1.0000 - val_loss: 0.1328
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9474 - loss: 0.1765 - val_accuracy: 1.0000 - val_loss: 0.1301
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.1997 - val_accuracy: 1.0000 - val_loss: 0.1275
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8947 - loss: 0.2543 - val_accuracy: 1.0000 - val_loss: 0.1254
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8947 - loss: 0.1926 - val_accuracy: 1.0000 - val_loss: 0.1233
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.1847 - val_accuracy: 1.0000 - val_loss: 0.1215
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.1808 - val_accuracy: 1.0000 - val_loss: 0.1199
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9474 - loss: 0.2951 - val_accuracy: 1.0000 - val_loss: 0.1180
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.2386 - val_accuracy: 1.0000 - val_loss: 0.1160
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.1449 - val_accuracy: 1.0000 - val_loss: 0.1137
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.2350 - val_accuracy: 1.0000 - val_loss: 0.1114
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8947 - loss: 0.1980 - val_accuracy: 1.0000 - val_loss: 0.1093
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9474 - loss: 0.2303 - val_accuracy: 1.0000 - val_loss: 0.1072
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8421 - loss: 0.2718 - val_accuracy: 1.0000 - val_loss: 0.1062
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9474 - loss: 0.1629 - val_accuracy: 1.0000 - val_loss: 0.1054
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.1890 - val_accuracy: 1.0000 - val_loss: 0.1045

In [25]:
print("\nFinal Validation Accuracy")

print(f"Full Batch : {history_full.history['val_accuracy'][-1]:.4f}")

print(f"SGD        : {history_sgd.history['val_accuracy'][-1]:.4f}")

print(f"Mini Batch : {history_mini.history['val_accuracy'][-1]:.4f}")

Final Validation Accuracy
Full Batch : 0.8000
SGD        : 1.0000
Mini Batch : 1.0000